import React, { useState } from "react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { 
  Edit, Car, Fuel, Settings, Palette, Calendar, FileText, 
  Image as ImageIcon, Gauge, Zap, ShieldCheck, CheckCircle2, 
  AlertTriangle, Clock, Download, ExternalLink, Trash2, X, DollarSign,
  TrendingUp, Wrench, Sparkles, ChevronRight, Eye
} from "lucide-react";
import { Vehicle } from "@/hooks/useVehicles";
import { useLocalStorage } from "@/hooks/useLocalStorage";
import { motion, AnimatePresence } from "framer-motion";

interface Contract {
  id: string;
  customerName: string;
  customerPhone?: string;
  customerNationalId?: string;
  vehicle: string;
  startDate: string;
  endDate: string;
  dailyRate?: number;
  totalAmount: string;
  status: string;
  statusColor: string;
  notes?: string;
}

interface VehicleDetailsDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  vehicle: Vehicle | null;
  onEdit: (vehicle: Vehicle) => void;
  onDelete?: (id: string) => Promise<boolean>;
}

const VehicleDetailsDialog: React.FC<VehicleDetailsDialogProps> = ({ 
  open, 
  onOpenChange, 
  vehicle, 
  onEdit, 
  onDelete 
}) => {
  const [contracts] = useLocalStorage<Contract[]>("contracts", []);
  const [selectedImageModal, setSelectedImageModal] = useState<string | null>(null);

  if (!vehicle) return null;

  const marque = vehicle.marque || vehicle.brand || "Véhicule";
  const modele = vehicle.modele || vehicle.model || "Standard";
  const immatriculation = vehicle.immatriculation || vehicle.registration || "Non spécifiée";
  const annee = vehicle.annee || vehicle.year || new Date().getFullYear();
  const etat = vehicle.etat_vehicule || "disponible";
  const photos = Array.isArray(vehicle.photos) ? vehicle.photos : [];
  const documents = Array.isArray(vehicle.documents) ? vehicle.documents : [];

  // Filter associated contracts
  const vehicleContracts = contracts.filter((contract) => {
    const vName = (contract.vehicle || '').toLowerCase();
    return (
      vName.includes(marque.toLowerCase()) ||
      vName.includes(modele.toLowerCase()) ||
      vName.includes(immatriculation.toLowerCase())
    );
  });

  // Calculate total revenue generated by this vehicle
  const totalRevenueGenerated = vehicleContracts.reduce((sum, c) => {
    const val = parseFloat((c.totalAmount || "0").replace(/[^0-9.-]+/g, ""));
    return isNaN(val) ? sum : sum + val;
  }, 0);

  // Status configuration
  const getStatusTheme = (status: string) => {
    switch (status) {
      case "disponible":
        return {
          label: "Disponible",
          badge: "bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30",
          dot: "bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.8)]"
        };
      case "loue":
        return {
          label: "En Location",
          badge: "bg-blue-500/15 text-blue-600 dark:text-blue-400 border-blue-500/30",
          dot: "bg-blue-500 shadow-[0_0_10px_rgba(59,130,246,0.8)]"
        };
      case "maintenance":
        return {
          label: "En Maintenance",
          badge: "bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/30",
          dot: "bg-amber-500 shadow-[0_0_10px_rgba(245,158,11,0.8)]"
        };
      case "horsService":
        return {
          label: "Hors Service",
          badge: "bg-rose-500/15 text-rose-600 dark:text-rose-400 border-rose-500/30",
          dot: "bg-rose-500 shadow-[0_0_10px_rgba(244,63,94,0.8)]"
        };
      default:
        return {
          label: "Disponible",
          badge: "bg-muted text-muted-foreground border-border/50",
          dot: "bg-muted-foreground"
        };
    }
  };

  const statusTheme = getStatusTheme(etat);

  // Next recommended oil change / service estimation
  const kmActuel = vehicle.kilometrage || 0;
  const kmProchaineVidange = Math.ceil((kmActuel + 1) / 10000) * 10000;
  const kmRestantVidange = Math.max(0, kmProchaineVidange - kmActuel);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-full max-w-5xl p-0 overflow-hidden border border-border/60 bg-card/95 backdrop-blur-2xl shadow-2xl rounded-3xl max-h-[92vh] flex flex-col">
        <DialogTitle className="sr-only">
          Passeport 360° du véhicule {marque} {modele} ({immatriculation})
        </DialogTitle>
        <DialogDescription className="sr-only">
          Fiche technique détaillée, documents légaux, historique des locations et carnet d'entretien.
        </DialogDescription>

        {/* 2026 Cockpit Hero Header */}
        <div className="relative bg-gradient-to-br from-card via-card to-accent/5 p-6 border-b border-border/40 shrink-0">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            {/* Vehicle Profile Info */}
            <div className="flex items-center gap-4">
              <div className="w-20 h-20 sm:w-24 sm:h-24 rounded-3xl overflow-hidden bg-muted/60 border-2 border-border/60 shadow-md shrink-0 relative group">
                {photos.length > 0 ? (
                  <img
                    src={photos[0]}
                    alt={`${marque} ${modele}`}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center">
                    <Car className="w-8 h-8 text-muted-foreground/40" />
                  </div>
                )}
              </div>

              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-[10px] font-black uppercase tracking-widest px-2.5 py-0.5 rounded-full bg-accent/15 text-accent border border-accent/20">
                    Passeport Flotte 2026
                  </span>
                  <div className={`inline-flex items-center gap-1.5 px-3 py-0.5 rounded-full border text-xs font-bold ${statusTheme.badge}`}>
                    <span className={`w-2 h-2 rounded-full ${statusTheme.dot}`} />
                    <span>{statusTheme.label}</span>
                  </div>
                </div>

                <h2 className="text-2xl sm:text-3xl font-black text-foreground tracking-tight">
                  {marque} <span className="text-accent">{modele}</span>
                </h2>

                <div className="flex flex-wrap items-center gap-2 mt-1.5 text-xs text-muted-foreground font-medium">
                  <span className="font-mono font-black px-2.5 py-0.5 rounded-lg bg-muted text-foreground border border-border/60">
                    {immatriculation}
                  </span>
                  <span>•</span>
                  <span className="font-bold">{annee}</span>
                  <span>•</span>
                  <span>{vehicle.couleur || "Blanc"}</span>
                </div>
              </div>
            </div>

            {/* Price & Actions */}
            <div className="flex items-center gap-3 self-end md:self-center">
              <div className="text-right px-4 py-2 rounded-2xl bg-accent/10 border border-accent/20">
                <div className="text-2xl font-black text-accent leading-none">
                  {vehicle.prix_par_jour || 200}
                  <span className="text-xs font-bold ml-1">DH</span>
                </div>
                <span className="text-[9px] uppercase font-bold text-muted-foreground tracking-wider block mt-0.5">
                  Tarif journalier
                </span>
              </div>

              <Button
                onClick={() => {
                  onEdit(vehicle);
                  onOpenChange(false);
                }}
                className="rounded-2xl h-11 px-5 bg-foreground text-background hover:bg-foreground/90 font-black text-xs shadow-md transition-transform active:scale-95"
              >
                <Edit className="w-4 h-4 mr-1.5" />
                Modifier
              </Button>
            </div>
          </div>
        </div>

        {/* 2026 5-Tab System */}
        <Tabs defaultValue="specs" className="flex-1 flex flex-col overflow-hidden">
          <div className="px-6 border-b border-border/40 bg-muted/20 shrink-0">
            <TabsList className="h-12 bg-transparent p-0 gap-2 overflow-x-auto justify-start">
              <TabsTrigger 
                value="specs" 
                className="data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-xl px-4 text-xs font-bold"
              >
                <Gauge className="w-4 h-4 mr-1.5 text-accent" /> Fiche & Télémétrie
              </TabsTrigger>
              <TabsTrigger 
                value="photos" 
                className="data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-xl px-4 text-xs font-bold"
              >
                <ImageIcon className="w-4 h-4 mr-1.5 text-blue-500" /> Galerie HD ({photos.length})
              </TabsTrigger>
              <TabsTrigger 
                value="docs" 
                className="data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-xl px-4 text-xs font-bold"
              >
                <ShieldCheck className="w-4 h-4 mr-1.5 text-emerald-500" /> Documents Légaux
              </TabsTrigger>
              <TabsTrigger 
                value="contracts" 
                className="data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-xl px-4 text-xs font-bold"
              >
                <Calendar className="w-4 h-4 mr-1.5 text-purple-500" /> Historique Contrats ({vehicleContracts.length})
              </TabsTrigger>
              <TabsTrigger 
                value="health" 
                className="data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-xl px-4 text-xs font-bold"
              >
                <Wrench className="w-4 h-4 mr-1.5 text-amber-500" /> Carnet de Santé
              </TabsTrigger>
            </TabsList>
          </div>

          <div className="p-6 sm:p-8 overflow-y-auto flex-1 custom-scrollbar">
            {/* TAB 1: FICHE TECHNIQUE & TÉLÉMÉTRIE */}
            <TabsContent value="specs" className="mt-0 space-y-6">
              {/* Telemetry Highlight Cards */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="p-4 rounded-2xl bg-muted/30 border border-border/40">
                  <div className="flex items-center justify-between text-muted-foreground mb-1">
                    <span className="text-[10px] font-black uppercase tracking-wider">Carburant</span>
                    <Fuel className="w-4 h-4 text-accent" />
                  </div>
                  <p className="text-base font-black text-foreground">{vehicle.type_carburant || "Essence"}</p>
                </div>

                <div className="p-4 rounded-2xl bg-muted/30 border border-border/40">
                  <div className="flex items-center justify-between text-muted-foreground mb-1">
                    <span className="text-[10px] font-black uppercase tracking-wider">Boîte</span>
                    <Zap className="w-4 h-4 text-blue-500" />
                  </div>
                  <p className="text-base font-black text-foreground">{vehicle.boite_vitesse || "Manuelle"}</p>
                </div>

                <div className="p-4 rounded-2xl bg-muted/30 border border-border/40">
                  <div className="flex items-center justify-between text-muted-foreground mb-1">
                    <span className="text-[10px] font-black uppercase tracking-wider">Odomètre Actuel</span>
                    <Gauge className="w-4 h-4 text-emerald-500" />
                  </div>
                  <p className="text-base font-black text-foreground">{(kmActuel).toLocaleString()} km</p>
                </div>

                <div className="p-4 rounded-2xl bg-muted/30 border border-border/40">
                  <div className="flex items-center justify-between text-muted-foreground mb-1">
                    <span className="text-[10px] font-black uppercase tracking-wider">Km Départ (Achat)</span>
                    <Clock className="w-4 h-4 text-muted-foreground" />
                  </div>
                  <p className="text-base font-black text-foreground">{(vehicle.km_depart || 0).toLocaleString()} km</p>
                </div>
              </div>

              {/* Complete Specifications Grid */}
              <div className="rounded-3xl border border-border/60 bg-card p-5 space-y-4">
                <h4 className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                  <Sparkles className="w-3.5 h-3.5 text-accent" />
                  Caractéristiques Détaillées du Véhicule
                </h4>

                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 text-xs">
                  <div className="p-3 rounded-2xl bg-muted/20 border border-border/30">
                    <span className="text-muted-foreground text-[10px] uppercase font-bold block mb-0.5">Marque</span>
                    <span className="text-sm font-black text-foreground">{marque}</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-muted/20 border border-border/30">
                    <span className="text-muted-foreground text-[10px] uppercase font-bold block mb-0.5">Modèle Commercial</span>
                    <span className="text-sm font-black text-foreground">{modele}</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-muted/20 border border-border/30">
                    <span className="text-muted-foreground text-[10px] uppercase font-bold block mb-0.5">Immatriculation Officielle</span>
                    <span className="font-mono text-sm font-black text-accent">{immatriculation}</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-muted/20 border border-border/30">
                    <span className="text-muted-foreground text-[10px] uppercase font-bold block mb-0.5">Année de Circulation</span>
                    <span className="text-sm font-black text-foreground">{annee}</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-muted/20 border border-border/30">
                    <span className="text-muted-foreground text-[10px] uppercase font-bold block mb-0.5">Couleur Carrosserie</span>
                    <span className="text-sm font-black text-foreground">{vehicle.couleur || "Blanc"}</span>
                  </div>

                  <div className="p-3 rounded-2xl bg-muted/20 border border-border/30">
                    <span className="text-muted-foreground text-[10px] uppercase font-bold block mb-0.5">Date d'enregistrement</span>
                    <span className="text-sm font-black text-foreground">
                      {vehicle.created_at ? new Date(vehicle.created_at).toLocaleDateString('fr-FR') : "N/A"}
                    </span>
                  </div>
                </div>
              </div>

              {/* Financial Performance Widget */}
              <div className="p-5 rounded-3xl bg-gradient-to-r from-accent/15 via-accent/5 to-transparent border border-accent/20 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div>
                  <span className="text-[10px] font-black uppercase tracking-widest text-accent flex items-center gap-1.5">
                    <TrendingUp className="w-3.5 h-3.5" /> Rentabilité & Revenus Générés
                  </span>
                  <p className="text-sm font-medium text-muted-foreground mt-1">
                    Total accumulé sur l'ensemble des contrats de location passés et en cours
                  </p>
                </div>
                <div className="text-right bg-background/80 px-5 py-2.5 rounded-2xl border border-accent/20">
                  <span className="text-2xl font-black text-foreground tracking-tight">
                    {totalRevenueGenerated.toLocaleString()} <span className="text-xs text-accent">MAD</span>
                  </span>
                  <span className="text-[9px] uppercase font-bold text-muted-foreground block">
                    {vehicleContracts.length} contrat{vehicleContracts.length > 1 ? 's' : ''} associé{vehicleContracts.length > 1 ? 's' : ''}
                  </span>
                </div>
              </div>
            </TabsContent>

            {/* TAB 2: GALERIE HD */}
            <TabsContent value="photos" className="mt-0 space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-sm font-black text-foreground">Photos Haute Définition</h4>
                  <p className="text-xs text-muted-foreground">Cliquez sur une photo pour l'agrandir en mode plein écran.</p>
                </div>
                <Badge variant="secondary" className="font-bold text-xs">{photos.length} photo{photos.length > 1 ? 's' : ''}</Badge>
              </div>

              {photos.length === 0 ? (
                <div className="p-12 text-center rounded-3xl border border-dashed border-border/60 bg-muted/20 text-muted-foreground">
                  <ImageIcon className="w-12 h-12 mx-auto mb-3 text-muted-foreground/30" />
                  <p className="font-bold text-sm">Aucune photo pour ce véhicule</p>
                  <p className="text-xs mt-1">Modifiez le véhicule pour ajouter des photos de présentation.</p>
                </div>
              ) : (
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                  {photos.map((photo, idx) => (
                    <div 
                      key={idx} 
                      onClick={() => setSelectedImageModal(photo)}
                      className="relative aspect-4/3 rounded-2xl overflow-hidden border border-border/60 bg-muted cursor-pointer group shadow-sm hover:shadow-md transition-all"
                    >
                      <img src={photo} alt={`Photo ${idx + 1}`} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
                      <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                        <div className="p-2.5 rounded-full bg-white/20 backdrop-blur-md text-white">
                          <Eye className="w-5 h-5" />
                        </div>
                      </div>
                      {idx === 0 && (
                        <div className="absolute top-2 left-2 px-2.5 py-0.5 rounded-full bg-accent text-accent-foreground text-[10px] font-black shadow-md">
                          Photo Principale
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </TabsContent>

            {/* TAB 3: DOCUMENTS LÉGAUX */}
            <TabsContent value="docs" className="mt-0 space-y-4">
              <div>
                <h4 className="text-sm font-black text-foreground">Conformité Administrative & Pièces</h4>
                <p className="text-xs text-muted-foreground">Suivi des cartes grises, attestations d'assurance et contrôle technique.</p>
              </div>

              {documents.length === 0 ? (
                <div className="p-12 text-center rounded-3xl border border-dashed border-border/60 bg-muted/20 text-muted-foreground">
                  <FileText className="w-12 h-12 mx-auto mb-3 text-muted-foreground/30" />
                  <p className="font-bold text-sm">Aucun document numérique associé</p>
                  <p className="text-xs mt-1">Vous pouvez téléverser les documents légaux depuis l'éditeur de véhicule.</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {documents.map((docUrl, idx) => (
                    <div 
                      key={idx} 
                      className="flex items-center justify-between p-4 rounded-2xl bg-card border border-border/60 shadow-xs hover:border-accent/40 transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <div className="p-3 rounded-2xl bg-accent/10 text-accent">
                          <FileText className="w-5 h-5" />
                        </div>
                        <div>
                          <p className="text-sm font-black text-foreground">Document Officiel #{idx + 1}</p>
                          <p className="text-xs text-muted-foreground">Pièce justificative de flotte</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => window.open(docUrl, "_blank")}
                          className="rounded-xl font-bold text-xs h-9 px-4 border-border/60"
                        >
                          <ExternalLink className="w-3.5 h-3.5 mr-1.5" /> Ouvrir
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </TabsContent>

            {/* TAB 4: HISTORIQUE CONTRATS */}
            <TabsContent value="contracts" className="mt-0 space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-sm font-black text-foreground">Historique des Locations</h4>
                  <p className="text-xs text-muted-foreground">Registre des contrats liés à ce véhicule.</p>
                </div>
                <Badge variant="secondary" className="font-bold">{vehicleContracts.length} contrat{vehicleContracts.length > 1 ? 's' : ''}</Badge>
              </div>

              {vehicleContracts.length === 0 ? (
                <div className="p-12 text-center rounded-3xl border border-dashed border-border/60 bg-muted/20 text-muted-foreground">
                  <Calendar className="w-12 h-12 mx-auto mb-3 text-muted-foreground/30" />
                  <p className="font-bold text-sm">Aucun contrat enregistré pour ce véhicule</p>
                  <p className="text-xs mt-1">L'historique se mettra à jour automatiquement lors de la création d'un contrat.</p>
                </div>
              ) : (
                <div className="rounded-2xl border border-border/60 overflow-hidden bg-card">
                  <Table>
                    <TableHeader>
                      <TableRow className="bg-muted/40">
                        <TableHead className="font-black text-[10px] uppercase">N° Contrat</TableHead>
                        <TableHead className="font-black text-[10px] uppercase">Client</TableHead>
                        <TableHead className="font-black text-[10px] uppercase">Période</TableHead>
                        <TableHead className="font-black text-[10px] uppercase">Montant Total</TableHead>
                        <TableHead className="font-black text-[10px] uppercase text-right">Statut</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {vehicleContracts.map((contract) => (
                        <TableRow key={contract.id} className="hover:bg-muted/30">
                          <TableCell className="font-mono font-bold text-xs">{contract.id}</TableCell>
                          <TableCell className="font-bold text-xs">{contract.customerName}</TableCell>
                          <TableCell className="text-xs text-muted-foreground">
                            {new Date(contract.startDate).toLocaleDateString('fr-FR')} → {new Date(contract.endDate).toLocaleDateString('fr-FR')}
                          </TableCell>
                          <TableCell className="font-black text-xs text-foreground">{contract.totalAmount}</TableCell>
                          <TableCell className="text-right">
                            <Badge variant="secondary" className="font-bold text-[10px]">
                              {contract.status || "Terminé"}
                            </Badge>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              )}
            </TabsContent>

            {/* TAB 5: CARNET DE SANTÉ & MAINTENANCE */}
            <TabsContent value="health" className="mt-0 space-y-6">
              <div>
                <h4 className="text-sm font-black text-foreground">Diagnostic & Entretien Préventif</h4>
                <p className="text-xs text-muted-foreground">Estimation du cycle d'entretien basée sur le kilométrage réel.</p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {/* Vidange Moteur */}
                <div className="p-5 rounded-3xl bg-muted/30 border border-border/60 space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="p-2.5 rounded-xl bg-amber-500/10 text-amber-600">
                        <Wrench className="w-4 h-4" />
                      </div>
                      <span className="text-xs font-black uppercase text-foreground">Vidange Moteur & Filtres</span>
                    </div>
                    <Badge variant="outline" className="text-[10px] font-bold">
                      Tous les 10 000 km
                    </Badge>
                  </div>
                  <div className="space-y-1.5">
                    <div className="flex justify-between text-xs font-bold">
                      <span className="text-muted-foreground">Prochaine vidange estimée</span>
                      <span className="text-foreground">{kmProchaineVidange.toLocaleString()} km</span>
                    </div>
                    <div className="w-full bg-muted h-2 rounded-full overflow-hidden">
                      <div 
                        className="bg-amber-500 h-full rounded-full" 
                        style={{ width: `${Math.min(100, ((10000 - kmRestantVidange) / 10000) * 100)}%` }} 
                      />
                    </div>
                    <span className="text-[10px] text-muted-foreground font-medium block">
                      Reste environ {kmRestantVidange.toLocaleString()} km avant intervention
                    </span>
                  </div>
                </div>

                {/* Pneumatiques & Freinage */}
                <div className="p-5 rounded-3xl bg-muted/30 border border-border/60 space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-600">
                        <CheckCircle2 className="w-4 h-4" />
                      </div>
                      <span className="text-xs font-black uppercase text-foreground">Freinage & Pneumatiques</span>
                    </div>
                    <span className="text-[10px] font-black text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 px-2.5 py-0.5 rounded-full">
                      Bon état
                    </span>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Contrôle visuel recommandé à chaque retour de contrat de location.
                  </p>
                </div>
              </div>
            </TabsContent>
          </div>
        </Tabs>

        {/* Full Image Lightbox Modal */}
        {selectedImageModal && (
          <div 
            onClick={() => setSelectedImageModal(null)}
            className="fixed inset-0 z-50 bg-black/90 backdrop-blur-md flex items-center justify-center p-4 cursor-zoom-out"
          >
            <div className="relative max-w-4xl max-h-[85vh] rounded-3xl overflow-hidden shadow-2xl">
              <img src={selectedImageModal} alt="Zoom véhicule" className="w-full h-full object-contain" />
              <button 
                onClick={() => setSelectedImageModal(null)}
                aria-label="Fermer la photo"
                className="absolute top-4 right-4 p-2 rounded-full bg-black/60 text-white hover:bg-black"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
};

export default VehicleDetailsDialog;
